# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'fastlanedemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for fastlanedemo
  pod 'Toast', '~> 4.0.0'

  target 'fastlanedemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end